In [1]:

# Tratamiento de datos

import pandas as pd
pd.set_option('display.max_columns', None)

# ----------

# Funciones personalizadas

import sys
import os

# Ruta absoluta al directorio raíz del proyecto
project_root = os.path.abspath(os.path.join(".."))

# Añadimos la ruta al path de Python
sys.path.append(project_root)


from src.utils import eda_utils as se

Realizamos un análisis de calidad de los datos. Vamos uno por uno

**1. Behavior**

In [2]:
behavior = pd.read_csv('../data/01_raw/behavior.csv')

In [3]:
se.eda_preliminar(behavior)

,customer_id,avg_session_time,pages_per_session,cart_abandon_rate,return_rate,support_tickets,review_score,behavior_churn_signal
7368,CUST007369,1.04,18,0.34,0.25,0,4.27,0
2701,CUST002702,19.74,3,0.09,0.15,6,2.49,0
5243,CUST005244,5.78,9,0.91,0.15,1,2.49,0
19977,CUST019978,2.41,7,0.46,0.15,9,2.19,1
6190,CUST006191,5.43,1,0.34,0.14,0,2.65,0

---------------
DIMENSIONES
Nuestro conjunto de datos presenta un total de 25000 filas y 8 columnas
---------------
INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            25000 non-null  object
 1   avg_session_time       25000 non-null  float64
 2   pages_per_session      25000 non-null  int64
 3   cart_abandon_rate      25000 non-null  float64
 4   return_rate            25000 non-null  float64
 5   support_tickets        25000 non-null  int64
 6   review_score           25000 non-null  float64
 7   behavior_churn_signal  25000 non-null  int64
dtypes: float64(4), int64(3), object(1)
memory usage: 1.5+ MB

None

---------------
NULOS

customer_id              0.0
avg_session_time         0.0
pages_per_session        0.0
cart_abandon_rate        0.0
return_rate              0.0
support_tickets          0.0
review_score             0.0
behavior_churn_signal    0.0
dtype: float64

---------------
DUPLICADOS
Tenemos un total de 0 duplicados
---------------
FRECUENCIAS CATEGÓRICAS
CUSTOMER_ID
customer_id
CUST000001    1
CUST000002    1
CUST000003    1
CUST000004    1
CUST000005    1
             ..
CUST024996    1
CUST024997    1
CUST024998    1
CUST024999    1
CUST025000    1
Name: count, Length: 25000, dtype: int64
----------
---------------
ESTADISTICOS NUMÉRICOS

,count,mean,std,min,25%,50%,75%,max
avg_session_time,25000.0,10.468978,5.472970,1.0,5.69,10.49,15.20,20.0
pages_per_session,25000.0,13.080840,7.225421,1.0,7.00,13.00,19.00,25.0
cart_abandon_rate,25000.0,0.497954,0.287699,0.0,0.25,0.50,0.75,1.0
return_rate,25000.0,0.250166,0.144221,0.0,0.13,0.25,0.38,0.5
support_tickets,25000.0,5.011960,3.171722,0.0,2.00,5.00,8.00,10.0
review_score,25000.0,3.005011,1.157417,1.0,2.01,3.01,4.01,5.0
behavior_churn_signal,25000.0,0.344480,0.475208,0.0,0.00,0.00,1.00,1.0

**2. Customers**

In [4]:
customers = pd.read_csv('../data/01_raw/customers.csv')

In [5]:
se.eda_preliminar(customers)

,customer_id,age,gender,country,registration_date,loyalty_score,lifetime_value,churn_label
16880,CUST016881,33,Male,Brazil,2018-04-27,31.19,4752.34,0
11662,CUST011663,65,Other,France,2019-09-29,12.96,3894.30,0
16150,CUST016151,18,Male,India,2019-02-07,28.10,304.08,0
22094,CUST022095,35,Female,Canada,2019-07-27,10.28,17138.55,0
6258,CUST006259,70,Other,USA,2019-09-27,46.81,19728.48,0

---------------
DIMENSIONES
Nuestro conjunto de datos presenta un total de 25000 filas y 8 columnas
---------------
INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        25000 non-null  object
 1   age                25000 non-null  int64
 2   gender             25000 non-null  object
 3   country            25000 non-null  object
 4   registration_date  25000 non-null  object
 5   loyalty_score      25000 non-null  float64
 6   lifetime_value     25000 non-null  float64
 7   churn_label        25000 non-null  int64
dtypes: float64(2), int64(2), object(4)
memory usage: 1.5+ MB

None

---------------
NULOS

customer_id          0.0
age                  0.0
gender               0.0
country              0.0
registration_date    0.0
loyalty_score        0.0
lifetime_value       0.0
churn_label          0.0
dtype: float64

---------------
DUPLICADOS
Tenemos un total de 0 duplicados
---------------
FRECUENCIAS CATEGÓRICAS
CUSTOMER_ID
customer_id
CUST000001    1
CUST000002    1
CUST000003    1
CUST000004    1
CUST000005    1
             ..
CUST024996    1
CUST024997    1
CUST024998    1
CUST024999    1
CUST025000    1
Name: count, Length: 25000, dtype: int64
----------
GENDER
gender
Male      8411
Other     8346
Female    8243
Name: count, dtype: int64
----------
COUNTRY
country
France       3247
Brazil       3192
USA          3148
India        3122
Canada       3105
UK           3089
Australia    3069
Germany      3028
Name: count, dtype: int64
----------
REGISTRATION_DATE
registration_date
2018-06-24    30
2018-08-03    26
2019-06-28    26
2023-03-25    25
2019-07-03    24
              ..
2022-11-20     4
2019-06-03     4
2021-06-11     3
2020-12-24     3
2018-05-09     3
Name: count, Length: 2001, dtype: int64
----------
---------------
ESTADISTICOS NUMÉRICOS

,count,mean,std,min,25%,50%,75%,max
age,25000.0,43.981920,15.280646,18.00,31.0000,44.000,57.000,70.00
loyalty_score,25000.0,49.936116,28.728880,0.00,25.1275,49.995,74.680,100.00
lifetime_value,25000.0,10017.471257,5761.536508,100.33,5008.7750,10003.530,15020.435,19998.03
churn_label,25000.0,0.216360,0.411771,0.00,0.0000,0.000,0.000,1.00

**3. Products**

In [6]:
products = pd.read_csv('../data/01_raw/products.csv')

In [7]:
se.eda_preliminar(products)

     product_id        category   price  margin_percentage  popularity_score
774   PROD00775  Home & Kitchen  609.87              15.83             82.38
712   PROD00713          Beauty   84.01              30.60             18.74
479   PROD00480          Sports  706.16              12.06             67.34
1239  PROD01240     Electronics   83.54              20.50             26.10
1841  PROD01842          Beauty  461.07              23.50              3.44

---------------
DIMENSIONES
Nuestro conjunto de datos presenta un total de 2000 filas y 5 columnas
---------------
INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         2000 non-null   object
 1   category           2000 non-null   object
 2   price              2000 non-null   float64
 3   margin_percentage  2000 non-null   float64
 4   popularity_score   2000 non-null   float64
dtypes: float64(3), object(2)
memory usage: 78.3+ KB

None

---------------
NULOS

product_id           0.0
category             0.0
price                0.0
margin_percentage    0.0
popularity_score     0.0
dtype: float64

---------------
DUPLICADOS
Tenemos un total de 0 duplicados
---------------
FRECUENCIAS CATEGÓRICAS
PRODUCT_ID
product_id
PROD00001    1
PROD00002    1
PROD00003    1
PROD00004    1
PROD00005    1
            ..
PROD01996    1
PROD01997    1
PROD01998    1
PROD01999    1
PROD02000    1
Name: count, Length: 2000, dtype: int64
----------
CATEGORY
category
Automotive        268
Beauty            263
Fashion           260
Toys              253
Books             249
Sports            244
Home & Kitchen    239
Electronics       224
Name: count, dtype: int64
----------
---------------
ESTADISTICOS NUMÉRICOS

,count,mean,std,min,25%,50%,75%,max
price,2000.0,510.669275,284.710062,5.13,263.3375,520.695,757.955,999.72
margin_percentage,2000.0,22.254620,10.237902,5.00,13.3325,22.120,31.175,39.98
popularity_score,2000.0,49.011145,28.974415,0.00,23.6425,48.595,73.220,99.77

**4. Transactions**

In [8]:
transactions = pd.read_csv('../data/01_raw/transactions.csv')

In [9]:
se.eda_preliminar(transactions)

,transaction_id,customer_id,product_id,order_date,order_value,payment_method,device_type,discount_applied,shipping_delay_days,fraud_label
107372,TXN0107373,CUST002467,PROD01205,2022-09-09,215.28,Debit Card,Desktop,0.43,6,0
73072,TXN0073073,CUST000697,PROD01487,2023-03-20,276.37,Crypto,Desktop,0.34,8,0
64792,TXN0064793,CUST002388,PROD01177,2021-04-10,561.39,Crypto,Desktop,0.42,7,0
53986,TXN0053987,CUST013359,PROD00944,2022-12-05,30.62,PayPal,Mobile,0.10,5,0
50026,TXN0050027,CUST016994,PROD00963,2023-01-11,427.89,Credit Card,Tablet,0.16,0,0

---------------
DIMENSIONES
Nuestro conjunto de datos presenta un total de 150000 filas y 10 columnas
---------------
INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   transaction_id       150000 non-null  object
 1   customer_id          150000 non-null  object
 2   product_id           150000 non-null  object
 3   order_date           150000 non-null  object
 4   order_value          150000 non-null  float64
 5   payment_method       150000 non-null  object
 6   device_type          150000 non-null  object
 7   discount_applied     150000 non-null  float64
 8   shipping_delay_days  150000 non-null  int64
 9   fraud_label          150000 non-null  int64
dtypes: float64(2), int64(2), object(6)
memory usage: 11.4+ MB

None

---------------
NULOS

transaction_id         0.0
customer_id            0.0
product_id             0.0
order_date             0.0
order_value            0.0
payment_method         0.0
device_type            0.0
discount_applied       0.0
shipping_delay_days    0.0
fraud_label            0.0
dtype: float64

---------------
DUPLICADOS
Tenemos un total de 0 duplicados
---------------
FRECUENCIAS CATEGÓRICAS
TRANSACTION_ID
transaction_id
TXN0000001    1
TXN0000002    1
TXN0000003    1
TXN0000004    1
TXN0000005    1
             ..
TXN0149996    1
TXN0149997    1
TXN0149998    1
TXN0149999    1
TXN0150000    1
Name: count, Length: 150000, dtype: int64
----------
CUSTOMER_ID
customer_id
CUST008016    18
CUST017076    17
CUST024529    17
CUST017595    17
CUST006827    17
              ..
CUST015584     1
CUST013316     1
CUST009513     1
CUST008672     1
CUST006490     1
Name: count, Length: 24938, dtype: int64
----------
PRODUCT_ID
product_id
PROD01645    106
PROD00962    105
PROD00197    100
PROD00722    100
PROD01910     99
            ...
PROD00521     53
PROD00780     53
PROD00325     51
PROD00955     47
PROD01376     45
Name: count, Length: 2000, dtype: int64
----------
ORDER_DATE
order_date
2019-05-03    104
2019-08-27    103
2019-01-18    102
2022-09-10    101
2020-03-22    101
             ...
2023-11-13     53
2022-06-21     52
2020-05-06     52
2023-06-27     48
2023-07-23     47
Name: count, Length: 2001, dtype: int64
----------
PAYMENT_METHOD
payment_method
PayPal         30195
Crypto         30011
UPI            30008
Debit Card     29923
Credit Card    29863
Name: count, dtype: int64
----------
DEVICE_TYPE
device_type
Mobile     50105
Tablet     50088
Desktop    49807
Name: count, dtype: int64
----------
---------------
ESTADISTICOS NUMÉRICOS

,count,mean,std,min,25%,50%,75%,max
order_value,150000.0,383.329265,229.337271,2.56,191.86,372.095,550.38,999.72
discount_applied,150000.0,0.250127,0.144323,0.00,0.12,0.250,0.38,0.50
shipping_delay_days,150000.0,5.006453,3.160721,0.00,2.00,5.000,8.00,10.00
fraud_label,150000.0,0.042207,0.201061,0.00,0.00,0.000,0.00,1.00